### ISSUE TITLE
CLI only accepts file path and not stdout

### ISSUE THREAD

**Issue by franciscoafonsoo** [Ambro17/graphql-schema-diff#23]
Hello @Ambro17 

Thank you so much for this tool, it has been very useful.

But something that has been a bit frustrating is trying to run this CLI against a file in the history of git or against a file is piped unix style.

So let's say i have a schema file `schema.graphqls` and i made a change to this file and commited it to git. It's the same file, so now i have no way of running `schemadiff` against this file using something like `git show HEAD:schema.graphqls`

The `schemadiff` should be able to handle the file outputted from pipes and it's useful to sometimes not have the file in the filesystem but directly piped from another cli.

Right now there is a way to do it using `mktemp`:

```sh
#!/bin/bash

if [ -z "$1" ]; then
    # $1 is not set or is empty
    echo "Error: Missing file path argument."
    echo "Usage: schema_change.sh <schema.graphqls_filepath>"
    exit 1
fi

# Create a temporary file
temp_file=$(mktemp)

# Retrieve the contents of the file from the commit and redirect the output to the temporary file
git show HEAD:$1 > $temp_file

# Pass the name of the temporary file as an argument to schemadiff
schemadiff -o $temp_file -n $1

# remove the temp file
rm $temp_file
```

**Comment by romeroyonatan** [comment]
Hi @franciscoafonsoo 

You could use file descriptors to avoid the temporal file. You can replace a file in the filesystem with the execution of a command using `<()`

for example

```sh
schemadiff -o <(git show HEAD:$1) -n $1
```

I hope that helps you :slightly_smiling_face:

**Comment by Ambro17** [comment]
Thank you Yona for the suggestion, i evaluated the implementation of such a feature and it's definitely possible but it would make the cli harder to understand in my opinion as one could not guess which of the two schemas should accept from `stdin`. With the suggestion above, the user has full control of which argument pipes from a process and which one reads from a file or any other combination. All without code changes
